### ISSUE TITLE
¿Qué rama es la estable?

### ISSUE THREAD

**Issue by alvarogonzalezsotillo** [FernandoGilVidal79/WorkTracker#4]
Estoy intentando compilar el proyecto con mono (para linux).

Habría que definir qué rama es la estable, porque tanto `develop` c35b4bb como `master` dfeda7d me dan problemas de compilación. Igual es que mono no es compatible, pero yo diría que sí son errores.

**Comment by alvarogonzalezsotillo** [comment]
```
  /home/alvaro/repos/WorkTracker/src/WorkTrackerAPI/Controllers/UserController.cs(82,18): error CS1061: 'Users' does not contain a definition for 'Departement' and no accessible extension method 'Departement' accepting a first argument of type 'Users' could be found (are you missing a using directive or an assembly reference?) [/home/alvaro/repos/WorkTracker/src/WorkTrackerAPI/WorkTrackerAPI.csproj]
  /home/alvaro/repos/WorkTracker/src/WorkTrackerAPI/Controllers/UserController.cs(82,38): error CS1061: 'Users' does not contain a definition for 'Departement' and no accessible extension method 'Departement' accepting a first argument of type 'Users' could be found (are you missing a using directive or an assembly reference?) [/home/alvaro/repos/WorkTracker/src/WorkTrackerAPI/WorkTrackerAPI.csproj]
```

**Comment by FernandoGilVidal79** [comment]
Buenas tardes.

Le echamos un vistazo y te avisamos. Develop es en la que trabajamos pero
no hemos mezclado con master

Un saludo

**Comment by FernandoGilVidal79** [comment]
Ahora mismo esta lo mismo en develop y en Master. Vamos a intentar hacer desarrollos en la rama develop y hacer fusiones a Master de funcionalidades completas

**Comment by alvarogonzalezsotillo** [comment]
Por si os interesa: parece que mono de linux funciona con vuestro proyecto :)

Si tenéis un usuario para probar avisadme y voy mirando.

![image](https://user-images.githubusercontent.com/1097236/200781939-8fbeda0c-b25b-4ff1-a476-6d09c1122b8b.png)
